---
- name: Cisco Enable password, Debug- Var,msg
  hosts: switches_distribution
  become: yes
  become_method: enable
  vars:
    ansible_become_pass: itsasecret
  tasks: 
    - name: Get facts
      debug: 
        msg:
          - "Hostname is : {{ansible_net_hostname}}"
          - "Image is: {{ansible_net_image}} "
    - name: Execute show command to test enable password
      ios_command:
        commands:
          - show run 
